/*
    @Date			              : 24.06.2020
    @Author                       : Stein Lundbeck
*/

using Creator.Components.TagHelpers.Icon.Models;
using SteinLundbeck.Components.Core.Components;
using SteinLundbeck.Components.Extensions;
using System.Collections.ObjectModel;

namespace Creator.Components.TagHelpers.Icon
{
    public interface IIconHelper
    {
        ITagBuilderCustom GetFontAwesomeTag(FontAwesomeIcon icon);

        ITagBuilderCustom GetFontAwesomeSixTag(FontAwesomeSixIcon icon);

        ITagBuilderCustom GetGoogleFontsIconsTag(GoogleFontsIcon icon);

        ITagBuilderCustom GetCssGGIconTag(CssGGIcons icon);

        ITagBuilderCustom GetIoniconsTag(Ionicons icon, IoniconsStyle style);
    }

    /// <summary>
    /// Contains different functions for the IconTagHelper
    /// </summary>
    public sealed class IconHelper : IIconHelper
    {
        private readonly ICollection<IIconRecordModel> _iconArchive;

        public IconHelper()
        {
            _iconArchive = new Collection<IIconRecordModel>();

            #region Icon records
            #region CSS GG
            _iconArchive.AddRange(new IIconRecordModel[] {
                new IconRecordModel(CssGGIcons.AddSquare, "gg-add-r"),
                new IconRecordModel(CssGGIcons.AddCircle, "gg-add"),
                new IconRecordModel(CssGGIcons.Adidas, "gg-adidas"),
                new IconRecordModel(CssGGIcons.Airplane, "gg-airplane"),
                new IconRecordModel(CssGGIcons.AlarmClock, "gg-alarm"),
                new IconRecordModel(CssGGIcons.Anchor, "gg-anchor"),
                new IconRecordModel(CssGGIcons.Album, "gg-album"),
                new IconRecordModel(CssGGIcons.AlignBottom, "gg-align-bottom"),
                new IconRecordModel(CssGGIcons.AlignTop, "gg-align-top"),
                new IconRecordModel(CssGGIcons.AlignCenter, "gg-align-center"),
                new IconRecordModel(CssGGIcons.AlignLeft, "gg-align-left"),
                new IconRecordModel(CssGGIcons.AlignRight, "gg-align-right"),
                new IconRecordModel(CssGGIcons.AlignMiddle, "gg-align-middle"),
                new IconRecordModel(CssGGIcons.AppleWatch, "gg-apple-watch"),
                new IconRecordModel(CssGGIcons.ArrowBottomLeft, "gg-arrow-bottom-left"),
                new IconRecordModel(CssGGIcons.ArrowBottomLeftSquare, "gg-arrow-bottom-left-r"),
                new IconRecordModel(CssGGIcons.ArrowBottomLeftCircle, "gg-arrow-bottom-left-o"),
                new IconRecordModel(CssGGIcons.ArrowBottomRight, "gg-arrow-bottom-right"),
                new IconRecordModel(CssGGIcons.ArrowBottomRightSquare, "gg-arrow-bottom-right-r"),
                new IconRecordModel(CssGGIcons.ArrowBottomRightCircle, "gg-arrow-bottom-right-o"),
                new IconRecordModel(CssGGIcons.ArrowTopLeft, "gg-arrow-top-left"),
                new IconRecordModel(CssGGIcons.ArrowTopLeftSquare, "gg-arrow-top-left-r"),
                new IconRecordModel(CssGGIcons.ArrowTopLeftCircle, "gg-arrow-top-left-o"),
                new IconRecordModel(CssGGIcons.ArrowDown, "gg-arrow-down"),
                new IconRecordModel(CssGGIcons.ArrowDownSquare, "gg-arrow-down-r"),
                new IconRecordModel(CssGGIcons.ArrowDownCircle, "gg-arrow-down-o"),
                new IconRecordModel(CssGGIcons.ArrowUp, "gg-arrow-up"),
                new IconRecordModel(CssGGIcons.ArrowUpSquare, "gg-arrow-up-r"),
                new IconRecordModel(CssGGIcons.ArrowUpCircle, "gg-arrow-up-o"),
                new IconRecordModel(CssGGIcons.ArrowLeft, "gg-arrow-left"),
                new IconRecordModel(CssGGIcons.ArrowLeftSquare, "gg-arrow-left-r"),
                new IconRecordModel(CssGGIcons.ArrowLeftCircle, "gg-arrow-left-o"),
                new IconRecordModel(CssGGIcons.ArrowRight, "gg-arrow-right"),
                new IconRecordModel(CssGGIcons.ArrowRightSquare, "gg-arrow-right-r"),
                new IconRecordModel(CssGGIcons.ArrowRightCircle, "gg-arrow-right-o"),
                new IconRecordModel(CssGGIcons.Attachment, "gg-attachment"),
                new IconRecordModel(CssGGIcons.Backspace, "gg-backspace"),
                new IconRecordModel(CssGGIcons.Battery, "gg-battery"),
                new IconRecordModel(CssGGIcons.BatteryEmpty, "gg-battery-empty"),
                new IconRecordModel(CssGGIcons.BatteryFull, "gg-battery-full"),
                new IconRecordModel(CssGGIcons.Bell, "gg-bell"),
                new IconRecordModel(CssGGIcons.Bitbucket, "gg-bitbucket"),
                new IconRecordModel(CssGGIcons.Block, "gg-block"),
                new IconRecordModel(CssGGIcons.BMW, "gg-bmw"),
                new IconRecordModel(CssGGIcons.Board, "gg-board"),
                new IconRecordModel(CssGGIcons.Bolt, "gg-bolt"),
                new IconRecordModel(CssGGIcons.Bowl, "gg-bowl"),
                new IconRecordModel(CssGGIcons.Bot, "gg-bot"),
                new IconRecordModel(CssGGIcons.Box, "gg-box"),
                new IconRecordModel(CssGGIcons.Brackets, "gg-brackets"),
                new IconRecordModel(CssGGIcons.Briefcase, "gg-briefcase"),
                new IconRecordModel(CssGGIcons.Browse, "gg-browse"),
                new IconRecordModel(CssGGIcons.Browser, "gg-browser"),
                new IconRecordModel(CssGGIcons.Brush, "gg-brush"),
                new IconRecordModel(CssGGIcons.Bulb, "gg-bulb"),
                new IconRecordModel(CssGGIcons.BarsMenu, "gg-menu"),
                new IconRecordModel(CssGGIcons.BarsMenuRound, "gg-menu-round"),
                new IconRecordModel(CssGGIcons.BarsMenuBoxed, "gg-menu-boxed"),
                new IconRecordModel(CssGGIcons.Cplusplus, "gg-c-plus-plus"),
                new IconRecordModel(CssGGIcons.Calculator, "gg-calculator"),
                new IconRecordModel(CssGGIcons.Calendar, "gg-calendar-dates"),
                new IconRecordModel(CssGGIcons.Camera, "gg-camera"),
                new IconRecordModel(CssGGIcons.Cap, "gg-cap"),
                new IconRecordModel(CssGGIcons.Chanel, "gg-chanel"),
                new IconRecordModel(CssGGIcons.Chart, "gg-chart"),
                new IconRecordModel(CssGGIcons.Check, "gg-check"),
                new IconRecordModel(CssGGIcons.CheckSquare, "gg-check-r"),
                new IconRecordModel(CssGGIcons.CheckCircle, "gg-check-o"),
                new IconRecordModel(CssGGIcons.ChevronDoubleDown, "gg-chevron-double-down"),
                new IconRecordModel(CssGGIcons.ChevronDoubleDownSquare, "gg-chevron-double-down-r"),
                new IconRecordModel(CssGGIcons.ChevronDoubleDownCircle, "gg-chevron-double-down-o"),
                new IconRecordModel(CssGGIcons.ChevronDoubleUp, "gg-chevron-double-up"),
                new IconRecordModel(CssGGIcons.ChevronDoubleUpSquare, "gg-chevron-double-up-r"),
                new IconRecordModel(CssGGIcons.ChevronDoubleUpCircle, "gg-chevron-double-up-o"),
                new IconRecordModel(CssGGIcons.ChevronDoubleLeft, "gg-chevron-double-left"),
                new IconRecordModel(CssGGIcons.ChevronDoubleLeftSquare, "gg-chevron-double-left-r"),
                new IconRecordModel(CssGGIcons.ChevronDoubleLeftCircle, "gg-chevron-double-left-o"),
                new IconRecordModel(CssGGIcons.ChevronDoubleRight, "gg-chevron-double-right"),
                new IconRecordModel(CssGGIcons.ChevronDoubleRightSquare, "gg-chevron-double-right-r"),
                new IconRecordModel(CssGGIcons.ChevronDoubleRightCircle, "gg-chevron-double-right-o"),
                new IconRecordModel(CssGGIcons.ChevronDown, "gg-chevron-down"),
                new IconRecordModel(CssGGIcons.ChevronDownSquare, "gg-chevron-down-r"),
                new IconRecordModel(CssGGIcons.ChevronDownCircle, "gg-chevron-down-o"),
                new IconRecordModel(CssGGIcons.ChevronUp, "gg-chevron-up"),
                new IconRecordModel(CssGGIcons.ChevronUpSquare, "gg-chevron-up-r"),
                new IconRecordModel(CssGGIcons.ChevronUpCircle, "gg-chevron-up-o"),
                new IconRecordModel(CssGGIcons.ChevronLeft, "gg-chevron-left"),
                new IconRecordModel(CssGGIcons.ChevronLeftSquare, "gg-chevron-left-r"),
                new IconRecordModel(CssGGIcons.ChevronLeftCircle, "gg-chevron-left-o"),
                new IconRecordModel(CssGGIcons.ChevronRight, "gg-chevron-right"),
                new IconRecordModel(CssGGIcons.ChevronRightSquare, "gg-chevron-right-r"),
                new IconRecordModel(CssGGIcons.ChevronRightCircle, "gg-chevron-right-o"),
                new IconRecordModel(CssGGIcons.Circleci, "gg-circleci"),
                new IconRecordModel(CssGGIcons.Clipboard, "gg-clipboard"),
                new IconRecordModel(CssGGIcons.Close, "gg-close"),
                new IconRecordModel(CssGGIcons.CloseSquare, "gg-close-r"),
                new IconRecordModel(CssGGIcons.CloseCircle, "gg-close-o"),
                new IconRecordModel(CssGGIcons.Cloud, "gg-cloud"),
                new IconRecordModel(CssGGIcons.Code, "gg-code-slash"),
                new IconRecordModel(CssGGIcons.Coffee, "gg-coffee"),
                new IconRecordModel(CssGGIcons.ComedyCentral, "gg-comedy-central"),
                new IconRecordModel(CssGGIcons.Comment, "gg-comment"),
                new IconRecordModel(CssGGIcons.Copy, "gg-copy"),
                new IconRecordModel(CssGGIcons.Copyright, "gg-copyright"),
                new IconRecordModel(CssGGIcons.CreditCard, "gg-credit-card"),
                new IconRecordModel(CssGGIcons.Crowdfire, "gg-crowdfire"),
                new IconRecordModel(CssGGIcons.Danger, "gg-danger"),
                new IconRecordModel(CssGGIcons.DarkMode, "gg-dark-mode"),
                new IconRecordModel(CssGGIcons.Database, "gg-database"),
                new IconRecordModel(CssGGIcons.Debug, "gg-debug"),
                new IconRecordModel(CssGGIcons.Designmodo, "gg-designmodo"),
                new IconRecordModel(CssGGIcons.Desktop, "gg-desktop"),
                new IconRecordModel(CssGGIcons.Dialpad, "gg-dialpad"),
                new IconRecordModel(CssGGIcons.DiceOne, "gg-dice-1"),
                new IconRecordModel(CssGGIcons.DiceTwo, "gg-dice-2"),
                new IconRecordModel(CssGGIcons.DiceThree, "gg-dice-3"),
                new IconRecordModel(CssGGIcons.DiceFour, "gg-dice-4"),
                new IconRecordModel(CssGGIcons.DiceFive, "gg-dice-5"),
                new IconRecordModel(CssGGIcons.DiceSix, "gg-dice-6"),
                new IconRecordModel(CssGGIcons.Digitalocean, "gg-digitalocean"),
                new IconRecordModel(CssGGIcons.DisplayGrid, "gg-display-grid"),
                new IconRecordModel(CssGGIcons.Dolby, "gg-dolby"),
                new IconRecordModel(CssGGIcons.Dollar, "gg-dollar"),
                new IconRecordModel(CssGGIcons.Drive, "gg-drive"),
                new IconRecordModel(CssGGIcons.Duplicate, "gg-duplicate"),
                new IconRecordModel(CssGGIcons.Erase, "gg-erase"),
                new IconRecordModel(CssGGIcons.Ereader, "gg-ereader"),
                new IconRecordModel(CssGGIcons.Ericsson, "gg-ericsson"),
                new IconRecordModel(CssGGIcons.Ethernet, "gg-ethernet"),
                new IconRecordModel(CssGGIcons.Euro, "gg-euro"),
                new IconRecordModel(CssGGIcons.Eventbrite, "gg-eventbrite"),
                new IconRecordModel(CssGGIcons.Export, "gg-export"),
                new IconRecordModel(CssGGIcons.Eye, "gg-eye"),
                new IconRecordModel(CssGGIcons.EyeAlt, "gg-enter-alt"),
                new IconRecordModel(CssGGIcons.Facebook, "gg-facebook"),
                new IconRecordModel(CssGGIcons.Feed, "gg-feed"),
                new IconRecordModel(CssGGIcons.Figma, "gg-figma"),
                new IconRecordModel(CssGGIcons.DocumentAdd, "gg-file-add"),
                new IconRecordModel(CssGGIcons.DocumentAlt, "gg-file-document"),
                new IconRecordModel(CssGGIcons.Document, "gg-file"),
                new IconRecordModel(CssGGIcons.DocumentRemove, "gg-file-remove"),
                new IconRecordModel(CssGGIcons.GenderFemale, "gg-gender-female"),
                new IconRecordModel(CssGGIcons.GenderMale, "gg-gender-male"),
                new IconRecordModel(CssGGIcons.Games, "gg-games"),
                new IconRecordModel(CssGGIcons.Ghost, "gg-ghost-character"),
                new IconRecordModel(CssGGIcons.Gift, "gg-gift"),
                new IconRecordModel(CssGGIcons.Globe, "gg-globe"),
                new IconRecordModel(CssGGIcons.GlobeAlt, "gg-globe-alt"),
                new IconRecordModel(CssGGIcons.Google, "gg-google"),
                new IconRecordModel(CssGGIcons.Hashtag, "gg-hashtag"),
                new IconRecordModel(CssGGIcons.Heart, "gg-heart"),
                new IconRecordModel(CssGGIcons.Home, "gg-home"),
                new IconRecordModel(CssGGIcons.HomeAlt, "gg-home-alt"),
                new IconRecordModel(CssGGIcons.Image, "gg-image"),
                new IconRecordModel(CssGGIcons.Import, "gg-import"),
                new IconRecordModel(CssGGIcons.Inbox, "gg-inbox"),
                new IconRecordModel(CssGGIcons.Infinity, "gg-infinity"),
                new IconRecordModel(CssGGIcons.Info, "gg-info"),
                new IconRecordModel(CssGGIcons.Insights, "gg-insights"),
                new IconRecordModel(CssGGIcons.Instagram, "gg-instagram"),
                new IconRecordModel(CssGGIcons.Key, "gg-key"),
                new IconRecordModel(CssGGIcons.Laptop, "gg-laptop"),
                new IconRecordModel(CssGGIcons.Link, "gg-link"),
                new IconRecordModel(CssGGIcons.List, "gg-layout-list"),
                new IconRecordModel(CssGGIcons.ListSquare, "gg-list"),
                new IconRecordModel(CssGGIcons.ListTree, "gg-list-tree"),
                new IconRecordModel(CssGGIcons.Loadbar, "gg-loadbar"),
                new IconRecordModel(CssGGIcons.LoadbarDoc, "gg-loadbar-doc"),
                new IconRecordModel(CssGGIcons.LoadbarSound, "gg-loadbar-sound"),
                new IconRecordModel(CssGGIcons.LockUnlocked, "gg-lock-unlock"),
                new IconRecordModel(CssGGIcons.LockLocked, "gg-lock"),
                new IconRecordModel(CssGGIcons.SignIn, "gg-log-in"),
                new IconRecordModel(CssGGIcons.SignOut, "gg-log-out"),
                new IconRecordModel(CssGGIcons.LogOff, "gg-log-off"),
                new IconRecordModel(CssGGIcons.Magnet, "gg-magnet"),
                new IconRecordModel(CssGGIcons.Envelope, "gg-mail"),
                new IconRecordModel(CssGGIcons.EnvelopeOpen, "gg-mail-open"),
                new IconRecordModel(CssGGIcons.Mic, "gg-mic"),
                new IconRecordModel(CssGGIcons.Microbit, "gg-microbit"),
                new IconRecordModel(CssGGIcons.Microsoft, "gg-microsoft"),
                new IconRecordModel(CssGGIcons.Moon, "gg-moon"),
                new IconRecordModel(CssGGIcons.Modem, "gg-modem"),
                new IconRecordModel(CssGGIcons.More, "gg-more-alt"),
                new IconRecordModel(CssGGIcons.MoreSquare, "gg-more-r"),
                new IconRecordModel(CssGGIcons.MoreCircle, "gg-more-o"),
                new IconRecordModel(CssGGIcons.MoveUp, "gg-move-up"),
                new IconRecordModel(CssGGIcons.MoveDown, "gg-move-down"),
                new IconRecordModel(CssGGIcons.MoveLeft, "gg-move-left"),
                new IconRecordModel(CssGGIcons.MoveRight, "gg-move-right"),
                new IconRecordModel(CssGGIcons.Note, "gg-music-note"),
                new IconRecordModel(CssGGIcons.NoteDouble, "gg-music"),
                new IconRecordModel(CssGGIcons.Speaker, "gg-music-speaker"),
                new IconRecordModel(CssGGIcons.Notes, "gg-notes"),
                new IconRecordModel(CssGGIcons.Notification, "gg-notifications"),
                new IconRecordModel(CssGGIcons.Npm, "gg-npm"),
                new IconRecordModel(CssGGIcons.Oculus, "gg-oculus"),
                new IconRecordModel(CssGGIcons.Settings, "gg-options"),
                new IconRecordModel(CssGGIcons.Organisation, "gg-organisation"),
                new IconRecordModel(CssGGIcons.Password, "gg-password"),
                new IconRecordModel(CssGGIcons.Patreon, "gg-patreon"),
                new IconRecordModel(CssGGIcons.PayPal, "gg-paypal"),
                new IconRecordModel(CssGGIcons.Pen, "gg-pen"),
                new IconRecordModel(CssGGIcons.Phone, "gg-phone"),
                new IconRecordModel(CssGGIcons.Play, "gg-play-button"),
                new IconRecordModel(CssGGIcons.PlaySquare, "gg-play-button-r"),
                new IconRecordModel(CssGGIcons.PlayCircle, "gg-play-button-o"),
                new IconRecordModel(CssGGIcons.Pause, "gg-play-pause"),
                new IconRecordModel(CssGGIcons.PauseSquare, "gg-play-pause-r"),
                new IconRecordModel(CssGGIcons.PauseCircle, "gg-play-pause-o"),
                new IconRecordModel(CssGGIcons.Stop, "gg-play-stop"),
                new IconRecordModel(CssGGIcons.StopSquare, "gg-play-stop-r"),
                new IconRecordModel(CssGGIcons.StopCircle, "gg-play-stop-o"),
                new IconRecordModel(CssGGIcons.Pokemon, "gg-pokemon"),
                new IconRecordModel(CssGGIcons.Polaroid, "gg-polaroid"),
                new IconRecordModel(CssGGIcons.Poll, "gg-poll"),
                new IconRecordModel(CssGGIcons.Printer, "gg-printer"),
                new IconRecordModel(CssGGIcons.Profile, "gg-profile"),
                new IconRecordModel(CssGGIcons.Radio, "gg-radio-check"),
                new IconRecordModel(CssGGIcons.RadioChecked, "gg-radio-checked"),
                new IconRecordModel(CssGGIcons.Ratio, "gg-ratio"),
                new IconRecordModel(CssGGIcons.Readme, "gg-readme"),
                new IconRecordModel(CssGGIcons.Redo, "gg-redo"),
                new IconRecordModel(CssGGIcons.QrCode, "gg-qr"),
                new IconRecordModel(CssGGIcons.RemoveSquare, "gg-remove-r"),
                new IconRecordModel(CssGGIcons.RemoveCircle, "gg-remove-o"),
                new IconRecordModel(CssGGIcons.Rename, "gg-rename"),
                new IconRecordModel(CssGGIcons.Repeat, "gg-repeat"),
                new IconRecordModel(CssGGIcons.Screen, "gg-screen"),
                new IconRecordModel(CssGGIcons.ScreenWide, "gg-screen-wide"),
                new IconRecordModel(CssGGIcons.Search, "gg-search-loading"),
                new IconRecordModel(CssGGIcons.Server, "gg-server"),
                new IconRecordModel(CssGGIcons.Smartphone, "gg-smartphone"),
                new IconRecordModel(CssGGIcons.SmileOpen, "gg-smile-mouth-open"),
                new IconRecordModel(CssGGIcons.SmileNeutral, "gg-smile-neutral"),
                new IconRecordModel(CssGGIcons.SmileNoMouth, "gg-smile-no-mouth"),
                new IconRecordModel(CssGGIcons.SmileNone, "gg-smile-none"),
                new IconRecordModel(CssGGIcons.SmileSad, "gg-smile-sad"),
                new IconRecordModel(CssGGIcons.SmileUpside, "gg-smile-upside"),
                new IconRecordModel(CssGGIcons.Smile, "gg-smile"),
                new IconRecordModel(CssGGIcons.Upload, "gg-software-upload"),
                new IconRecordModel(CssGGIcons.Download, "gg-software-download"),
                new IconRecordModel(CssGGIcons.Support, "gg-support"),
                new IconRecordModel(CssGGIcons.ToggleOn, "gg-togle-on"),
                new IconRecordModel(CssGGIcons.ToggleOff, "gg-togle-off"),
                new IconRecordModel(CssGGIcons.Trash, "gg-trash"),
                new IconRecordModel(CssGGIcons.TrashEmpty, "gg-trash-empty"),
                new IconRecordModel(CssGGIcons.TrendingUp, "gg-trending"),
                new IconRecordModel(CssGGIcons.TrendingDown, "gg-trending-down"),
                new IconRecordModel(CssGGIcons.TV, "gg-tv"),
                new IconRecordModel(CssGGIcons.Trello, "gg-trello"),
                new IconRecordModel(CssGGIcons.Twilio, "gg-twilio"),
                new IconRecordModel(CssGGIcons.Twitter, "gg-twitter"),
                new IconRecordModel(CssGGIcons.UiKit, "gg-ui-kit"),
                new IconRecordModel(CssGGIcons.Undo, "gg-undo"),
                new IconRecordModel(CssGGIcons.User, "gg-user"),
                new IconRecordModel(CssGGIcons.UserAdd, "gg-user-add"),
                new IconRecordModel(CssGGIcons.UserRemove, "gg-user-remove"),
                new IconRecordModel(CssGGIcons.UserList, "gg-user-list"),
                new IconRecordModel(CssGGIcons.ViewCols, "gg-view-cols"),
                new IconRecordModel(CssGGIcons.ViewComfortable, "gg-view-comfortable"),
                new IconRecordModel(CssGGIcons.ViewDay, "gg-view-day"),
                new IconRecordModel(CssGGIcons.ViewGrid, "gg-view-grid"),
                new IconRecordModel(CssGGIcons.ViewList, "gg-view-list"),
                new IconRecordModel(CssGGIcons.ViewMonth, "gg-view-month"),
                new IconRecordModel(CssGGIcons.ViewSplit, "gg-view-split"),
                new IconRecordModel(CssGGIcons.Website, "gg-website"),
                new IconRecordModel(CssGGIcons.Windows, "gg-windows"),
                new IconRecordModel(CssGGIcons.Work, "gg-work-alt"),
                new IconRecordModel(CssGGIcons.YinYang, "gg-yinyang"),
                new IconRecordModel(CssGGIcons.YouTube, "gg-youtube"),
                new IconRecordModel(CssGGIcons.Zoom, "gg-zoom-in"),
                new IconRecordModel(CssGGIcons.ZoomOut, "gg-zoom-out"),
                new IconRecordModel(CssGGIcons.Pexels, "gg-pexels")
            });
            #endregion

            #region Google Font Material
            _iconArchive.AddRange(new IIconRecordModel[]
            {
                new IconRecordModel(GoogleFontsIcon.Search, "search"),
                new IconRecordModel(GoogleFontsIcon.Home, "home"),
                new IconRecordModel(GoogleFontsIcon.Bars, "menu"),
                new IconRecordModel(GoogleFontsIcon.Close, "close"),
                new IconRecordModel(GoogleFontsIcon.Settings, "settings"),
                new IconRecordModel(GoogleFontsIcon.ShoppingCart, "shopping_cart"),
                new IconRecordModel(GoogleFontsIcon.ShoppingCartAdd, "add_shopping_cart"),
                new IconRecordModel(GoogleFontsIcon.ShoppingCartCheckout, "shopping_cart_checkout"),
                new IconRecordModel(GoogleFontsIcon.ShoppingBag, "shopping_bag"),
                new IconRecordModel(GoogleFontsIcon.Payments, "payments"),
                new IconRecordModel(GoogleFontsIcon.CreditCard, "credit_card"),
                new IconRecordModel(GoogleFontsIcon.ArrowLeft, "arrow_back"),
                new IconRecordModel(GoogleFontsIcon.ArrowRight, "arrow_forward"),
                new IconRecordModel(GoogleFontsIcon.ArrowUp, "arrow_upward"),
                new IconRecordModel(GoogleFontsIcon.ArrowDown, "arrow_downward"),
                new IconRecordModel(GoogleFontsIcon.Check, "check"),
                new IconRecordModel(GoogleFontsIcon.CheckBox, "check_box"),
                new IconRecordModel(GoogleFontsIcon.AngleLeft, "chevron_left"),
                new IconRecordModel(GoogleFontsIcon.AngleRight, "chevron_right"),
                new IconRecordModel(GoogleFontsIcon.AngleUp, "expand_less"),
                new IconRecordModel(GoogleFontsIcon.AngleDown, "expand_more"),
                new IconRecordModel(GoogleFontsIcon.Login, "login"),
                new IconRecordModel(GoogleFontsIcon.Logout, "logout"),
                new IconRecordModel(GoogleFontsIcon.Refresh, "refresh"),
                new IconRecordModel(GoogleFontsIcon.Mail, "mail"),
                new IconRecordModel(GoogleFontsIcon.MailUnsubscribe, "unsubscribe"),
                new IconRecordModel(GoogleFontsIcon.Image, "image"),
                new IconRecordModel(GoogleFontsIcon.Images, "photo_library"),
                new IconRecordModel(GoogleFontsIcon.ImagePanorama, "panorama"),
                new IconRecordModel(GoogleFontsIcon.Grid, "grid_on"),
                new IconRecordModel(GoogleFontsIcon.GridSmall, "background_grid_small"),
                new IconRecordModel(GoogleFontsIcon.User, "person"),
                new IconRecordModel(GoogleFontsIcon.UserGroup, "group"),
                new IconRecordModel(GoogleFontsIcon.UserGroups, "groups"),
                new IconRecordModel(GoogleFontsIcon.UserAdd, "person_add"),
                new IconRecordModel(GoogleFontsIcon.UserCircle, "account_circle"),
                new IconRecordModel(GoogleFontsIcon.UserBox, "account_box"),
                new IconRecordModel(GoogleFontsIcon.UserSettings, "manage_accounts"),
                new IconRecordModel(GoogleFontsIcon.UserRemove, "person_cancel"),
                new IconRecordModel(GoogleFontsIcon.UserCheck, "person_check"),
                new IconRecordModel(GoogleFontsIcon.UserSearch, "person_search"),
                new IconRecordModel(GoogleFontsIcon.UserMail, "contact_mail"),
                new IconRecordModel(GoogleFontsIcon.Psychology, "psychology"),
                new IconRecordModel(GoogleFontsIcon.Man, "man"),
                new IconRecordModel(GoogleFontsIcon.Woman, "woman"),
                new IconRecordModel(GoogleFontsIcon.InfoCircle, "info"),
                new IconRecordModel(GoogleFontsIcon.Warning, "warning"),
                new IconRecordModel(GoogleFontsIcon.HelpCircle, "help"),
                new IconRecordModel(GoogleFontsIcon.Language, "language"),
                new IconRecordModel(GoogleFontsIcon.ErrorCircle, "error"),
                new IconRecordModel(GoogleFontsIcon.Lightbulb, "lightbulb"),
                new IconRecordModel(GoogleFontsIcon.Calendar, "calendar_month"),
                new IconRecordModel(GoogleFontsIcon.Code, "code"),
                new IconRecordModel(GoogleFontsIcon.Upload, "upload_file"),
                new IconRecordModel(GoogleFontsIcon.Preview, "preview"),
                new IconRecordModel(GoogleFontsIcon.List, "lists"),
                new IconRecordModel(GoogleFontsIcon.ListFormatted, "format_list_bulleted"),
                new IconRecordModel(GoogleFontsIcon.ListFormattedNumbered, "format_list_numbered"),
                new IconRecordModel(GoogleFontsIcon.Chat, "chat"),
                new IconRecordModel(GoogleFontsIcon.Comment, "comment"),
                new IconRecordModel(GoogleFontsIcon.Link, "link"),
                new IconRecordModel(GoogleFontsIcon.Hub, "hub"),
                new IconRecordModel(GoogleFontsIcon.Phone, "call"),
                new IconRecordModel(GoogleFontsIcon.Contacts, "contacts"),
                new IconRecordModel(GoogleFontsIcon.TuneSettings, "tune"),
                new IconRecordModel(GoogleFontsIcon.Database, "database"),
                new IconRecordModel(GoogleFontsIcon.BarChart, "bar_chart"),
                new IconRecordModel(GoogleFontsIcon.AccountTree, "account_tree"),
                new IconRecordModel(GoogleFontsIcon.Copyright, "copyright"),
                new IconRecordModel(GoogleFontsIcon.Document, "description"),
                new IconRecordModel(GoogleFontsIcon.Copy, "content_copy"),
                new IconRecordModel(GoogleFontsIcon.AttachFile, "attach_file"),
                new IconRecordModel(GoogleFontsIcon.AttachFileAdd, "attach_file_add"),
                new IconRecordModel(GoogleFontsIcon.Article, "article"),
                new IconRecordModel(GoogleFontsIcon.Tag, "tag"),
                new IconRecordModel(GoogleFontsIcon.Football, "sports_soccer"),
                new IconRecordModel(GoogleFontsIcon.Basketball, "sports_basketball"),
                new IconRecordModel(GoogleFontsIcon.Save, "save"),
                new IconRecordModel(GoogleFontsIcon.Cellphone, "smartphone"),
                new IconRecordModel(GoogleFontsIcon.CellphoneAndroid, "phone_android"),
                new IconRecordModel(GoogleFontsIcon.Computer, "computer"),
                new IconRecordModel(GoogleFontsIcon.Laptop, "laptop_mac"),
                new IconRecordModel(GoogleFontsIcon.Monitor, "monitor"),
                new IconRecordModel(GoogleFontsIcon.Airplane, "airplanemode_active"),
                new IconRecordModel(GoogleFontsIcon.Family, "family_restroom"),
                new IconRecordModel(GoogleFontsIcon.Security, "security"),
                new IconRecordModel(GoogleFontsIcon.Shield, "shield"),
                new IconRecordModel(GoogleFontsIcon.Verified, "verified_user"),
                new IconRecordModel(GoogleFontsIcon.FileOpen, "file_open"),
                new IconRecordModel(GoogleFontsIcon.Dataset, "dataset"),
                new IconRecordModel(GoogleFontsIcon.DatasetLinked, "dataset_linked"),
                new IconRecordModel(GoogleFontsIcon.Javascript, "javascript"),
                new IconRecordModel(GoogleFontsIcon.CSS, "css"),
                new IconRecordModel(GoogleFontsIcon.ABC, "abc"),
                new IconRecordModel(GoogleFontsIcon.CheckSmall, "check_small"),
                new IconRecordModel(GoogleFontsIcon.HeartCheck, "heart_check"),
                new IconRecordModel(GoogleFontsIcon.EventList, "event_list")
            });
            #endregion

            #region Font Awesome
            _iconArchive.AddRange(new IIconRecordModel[] {
                new IconRecordModel(FontAwesomeIcon.Box, "box"),
                new IconRecordModel(FontAwesomeIcon.BoxOpen, "box-open"),
                new IconRecordModel(FontAwesomeIcon.Boxes, "boxes"),
                new IconRecordModel(FontAwesomeIcon.Tools, "tools"),
                new IconRecordModel(FontAwesomeIcon.Save, "save", "far"),
                new IconRecordModel(FontAwesomeIcon.SaveFull, "save"),
                new IconRecordModel(FontAwesomeIcon.Close, "window-close", "far"),
                new IconRecordModel(FontAwesomeIcon.CloseFull, "save"),
                new IconRecordModel(FontAwesomeIcon.CloseCircle, "times-circle", "far"),
                new IconRecordModel(FontAwesomeIcon.CloseCircleFull, "save"),
                new IconRecordModel(FontAwesomeIcon.Camera, "camera"),
                new IconRecordModel(FontAwesomeIcon.BorderAll, "border-all"),
                new IconRecordModel(FontAwesomeIcon.SignIn, "sign-in-alt"),
                new IconRecordModel(FontAwesomeIcon.SignOut, "sign-out-alt"),
                new IconRecordModel(FontAwesomeIcon.Doc, "file-alt", "far"),
                new IconRecordModel(FontAwesomeIcon.DocCode, "file-code", "far"),
                new IconRecordModel(FontAwesomeIcon.DocImage, "file-image", "far"),
                new IconRecordModel(FontAwesomeIcon.DocPDF, "file-pdf", "far"),
                new IconRecordModel(FontAwesomeIcon.FileUpload, "file-upload"),
                new IconRecordModel(FontAwesomeIcon.FileDownload, "file-download"),
                new IconRecordModel(FontAwesomeIcon.FileExport, "file-export"),
                new IconRecordModel(FontAwesomeIcon.Lock, "lock"),
                new IconRecordModel(FontAwesomeIcon.LockOpen, "lock-open"),
                new IconRecordModel(FontAwesomeIcon.Edit, "edit", "far"),
                new IconRecordModel(FontAwesomeIcon.EditFull, "edit"),
                new IconRecordModel(FontAwesomeIcon.Copy, "copy", "far"),
                new IconRecordModel(FontAwesomeIcon.CopyFull, "copy"),
                new IconRecordModel(FontAwesomeIcon.Cogs, "cogs"),
                new IconRecordModel(FontAwesomeIcon.X, "times"),
                new IconRecordModel(FontAwesomeIcon.ArrowLeft, "arrow-left"),
                new IconRecordModel(FontAwesomeIcon.ArrowRight, "arrow-right"),
                new IconRecordModel(FontAwesomeIcon.ArrowUp, "arrow-up"),
                new IconRecordModel(FontAwesomeIcon.ArrowDown, "arrow-down"),
                new IconRecordModel(FontAwesomeIcon.AngleLeft, "angle-left"),
                new IconRecordModel(FontAwesomeIcon.AngleRight, "angle-right"),
                new IconRecordModel(FontAwesomeIcon.AngleUp, "angle-up"),
                new IconRecordModel(FontAwesomeIcon.AngleDown, "angle-down"),
                new IconRecordModel(FontAwesomeIcon.Calendar, "calendar-alt", "far"),
                new IconRecordModel(FontAwesomeIcon.CalendarFull, "calendar-alt"),
                new IconRecordModel(FontAwesomeIcon.Building, "building", "far"),
                new IconRecordModel(FontAwesomeIcon.BuildingFull, "building"),
                new IconRecordModel(FontAwesomeIcon.Envelope, "envelope", "far"),
                new IconRecordModel(FontAwesomeIcon.EnvelopeFull, "envelope"),
                new IconRecordModel(FontAwesomeIcon.EnvelopeOpen, "envelope-open", "far"),
                new IconRecordModel(FontAwesomeIcon.EnvelopeOpenFull, "envelope-open"),
                new IconRecordModel(FontAwesomeIcon.AddressCard, "address-card", "far"),
                new IconRecordModel(FontAwesomeIcon.AddressCardFull, "address-card"),
                new IconRecordModel(FontAwesomeIcon.Phone, "phone"),
                new IconRecordModel(FontAwesomeIcon.PhoneFull, "phone-square"),
                new IconRecordModel(FontAwesomeIcon.Mobile, "mobile-alt"),
                new IconRecordModel(FontAwesomeIcon.MobileFull, "mobile"),
                new IconRecordModel(FontAwesomeIcon.Messenger, "facebook-messenger", "fab"),
                new IconRecordModel(FontAwesomeIcon.LaptopCode, "laptop-code"),
                new IconRecordModel(FontAwesomeIcon.Comment, "comment", "far"),
                new IconRecordModel(FontAwesomeIcon.CommentFull, "comment"),
                new IconRecordModel(FontAwesomeIcon.Comments, "comments", "far"),
                new IconRecordModel(FontAwesomeIcon.CommentsFull, "comments"),
                new IconRecordModel(FontAwesomeIcon.CreditCard, "credit-card"),
                new IconRecordModel(FontAwesomeIcon.Like, "thumbs-up", "far"),
                new IconRecordModel(FontAwesomeIcon.LikeFull, "thumbs-up"),
                new IconRecordModel(FontAwesomeIcon.List, "list"),
                new IconRecordModel(FontAwesomeIcon.ListAlt, "list-alt", "far"),
                new IconRecordModel(FontAwesomeIcon.ListAltFull, "list-alt"),
                new IconRecordModel(FontAwesomeIcon.Home, "home"),
                new IconRecordModel(FontAwesomeIcon.HomeDamage, "house-damage"),
                new IconRecordModel(FontAwesomeIcon.Ghost, "ghost"),
                new IconRecordModel(FontAwesomeIcon.Bars, "bars"),
                new IconRecordModel(FontAwesomeIcon.Gear, "gear"),
                new IconRecordModel(FontAwesomeIcon.GitHub, "github", "fab"),
                new IconRecordModel(FontAwesomeIcon.Globe, "globe"),
                new IconRecordModel(FontAwesomeIcon.GlobeEurope, "globe-europe"),
                new IconRecordModel(FontAwesomeIcon.AddressBook, "address-book", "far"),
                new IconRecordModel(FontAwesomeIcon.AddressBookFull, "address-book"),
                new IconRecordModel(FontAwesomeIcon.Folder, "folder", "far"),
                new IconRecordModel(FontAwesomeIcon.FolderFull, "folder"),
                new IconRecordModel(FontAwesomeIcon.FolderMinusFull, "folder-minus"),
                new IconRecordModel(FontAwesomeIcon.FolderPlusFull, "folder-plus"),
                new IconRecordModel(FontAwesomeIcon.FolderOpen, "folder-open", "far"),
                new IconRecordModel(FontAwesomeIcon.FileImage, "file-image", "far"),
                new IconRecordModel(FontAwesomeIcon.FileImageFull, "file-image"),
                new IconRecordModel(FontAwesomeIcon.FileAlt, "file-alt", "far"),
                new IconRecordModel(FontAwesomeIcon.FolderOpenFull, "folder-open"),
                new IconRecordModel(FontAwesomeIcon.UserCircle, "user-circle", "far"),
                new IconRecordModel(FontAwesomeIcon.UserCircleFull, "user-circle"),
                new IconRecordModel(FontAwesomeIcon.UserNinja, "user-ninja"),
                new IconRecordModel(FontAwesomeIcon.UserSpy, "user-secret"),
                new IconRecordModel(FontAwesomeIcon.UserTie, "user-tie"),
                new IconRecordModel(FontAwesomeIcon.User, "user", "far"),
                new IconRecordModel(FontAwesomeIcon.UserFull, "user"),
                new IconRecordModel(FontAwesomeIcon.Code, "code"),
                new IconRecordModel(FontAwesomeIcon.Diagram, "project-diagram"),
                new IconRecordModel(FontAwesomeIcon.Add, "plus-square", "far"),
                new IconRecordModel(FontAwesomeIcon.AddFull, "plus-square"),
                new IconRecordModel(FontAwesomeIcon.AddCircle, "plus-circle", "far"),
                new IconRecordModel(FontAwesomeIcon.AddCircleFull, "plus-circle"),
                new IconRecordModel(FontAwesomeIcon.ShoppingBasket, "shopping-basket"),
                new IconRecordModel(FontAwesomeIcon.ShoppingCart, "shopping-cart"),
                new IconRecordModel(FontAwesomeIcon.ShoppingCartPlus, "cart-plus"),
                new IconRecordModel(FontAwesomeIcon.ShoppingBag, "shopping-bag"),
                new IconRecordModel(FontAwesomeIcon.Handshake, "handshake"),
                new IconRecordModel(FontAwesomeIcon.HandshakeFull, "handshake", "far"),
                new IconRecordModel(FontAwesomeIcon.ThumbsUp, "thumbs-up", "far"),
                new IconRecordModel(FontAwesomeIcon.ThumbsUpFull, "thumbs-up"),
                new IconRecordModel(FontAwesomeIcon.ThumbsDown, "thumbs-down", "far"),
                new IconRecordModel(FontAwesomeIcon.ThumbsDownFull, "thumbs-down"),
                new IconRecordModel(FontAwesomeIcon.MoneyBill, "money-bill"),
                new IconRecordModel(FontAwesomeIcon.Truck, "truck"),
                new IconRecordModel(FontAwesomeIcon.Tasks, "tasks"),
                new IconRecordModel(FontAwesomeIcon.Visa, "cc-visa", "fab"),
                new IconRecordModel(FontAwesomeIcon.Stripe, "cc-stripe", "fab"),
                new IconRecordModel(FontAwesomeIcon.PayPal, "cc-paypal", "fab"),
                new IconRecordModel(FontAwesomeIcon.PayPalIcon, "paypal", "fab"),
                new IconRecordModel(FontAwesomeIcon.Mastercard, "cc-mastercard", "fab"),
                new IconRecordModel(FontAwesomeIcon.ApplePay, "cc-apple-pay", "fab"),
                new IconRecordModel(FontAwesomeIcon.ApplePayIcon, "apple-pay", "fab"),
                new IconRecordModel(FontAwesomeIcon.AmericanExpress, "cc-amex", "fab"),
                new IconRecordModel(FontAwesomeIcon.AmazonPay, "cc-amazon-pay", "fab"),
                new IconRecordModel(FontAwesomeIcon.AmazonPayIcon, "amazon-pay", "fab"),
                new IconRecordModel(FontAwesomeIcon.GoogleWallet, "google-wallet", "fab"),
                new IconRecordModel(FontAwesomeIcon.Download, "download"),
                new IconRecordModel(FontAwesomeIcon.Upload, "upload"),
                new IconRecordModel(FontAwesomeIcon.UploadCloud, "cloud-upload-alt"),
                new IconRecordModel(FontAwesomeIcon.DownloadCloud, "cloud-download-alt"),
                new IconRecordModel(FontAwesomeIcon.Bullhorn, "bullhorn"),
                new IconRecordModel(FontAwesomeIcon.Smile, "smile", "far"),
                new IconRecordModel(FontAwesomeIcon.SmileFull, "smile"),
                new IconRecordModel(FontAwesomeIcon.SmileWink, "smile-wink", "far"),
                new IconRecordModel(FontAwesomeIcon.SmileWinkFull, "smile-wink"),
                new IconRecordModel(FontAwesomeIcon.SmileLaugh, "grin", "far"),
                new IconRecordModel(FontAwesomeIcon.SmileLaughFull, "grin"),
                new IconRecordModel(FontAwesomeIcon.UserPlusFull, "user-plus"),
                new IconRecordModel(FontAwesomeIcon.Check, "check"),
                new IconRecordModel(FontAwesomeIcon.CheckSquare, "check-square"),
                new IconRecordModel(FontAwesomeIcon.CheckSquareFull, "check-square"),
                new IconRecordModel(FontAwesomeIcon.CheckCircle, "check-circle", "far"),
                new IconRecordModel(FontAwesomeIcon.CheckCircleFull, "check-circle"),
                new IconRecordModel(FontAwesomeIcon.UserShield, "user-shield"),
                new IconRecordModel(FontAwesomeIcon.Search, "search"),
                new IconRecordModel(FontAwesomeIcon.SearchPlus, "search-plus"),
                new IconRecordModel(FontAwesomeIcon.SearchMinus, "search-minus"),
                new IconRecordModel(FontAwesomeIcon.SearchDollar, "search-dollar"),
                new IconRecordModel(FontAwesomeIcon.SearchLocation, "search-location"),
                new IconRecordModel(FontAwesomeIcon.ShieldVirus, "shield-virus"),
                new IconRecordModel(FontAwesomeIcon.ShieldAlt, "shield-alt"),
                new IconRecordModel(FontAwesomeIcon.UserLock, "user-lock"),
                new IconRecordModel(FontAwesomeIcon.Thumbstick, "thumbstick"),
                new IconRecordModel(FontAwesomeIcon.FacebookLogo, "facebook-f", "fab"),
                new IconRecordModel(FontAwesomeIcon.FacebookLogoCircle, "facebook", "fab"),
                new IconRecordModel(FontAwesomeIcon.FacebookLogoSquare, "facebook-square", "fab"),
                new IconRecordModel(FontAwesomeIcon.LinkedInLogo, "linkedin-in", "fab"),
                new IconRecordModel(FontAwesomeIcon.LinkedInLogoSquare, "linkedin", "fab"),
                new IconRecordModel(FontAwesomeIcon.DeleteTrash, "trash-alt", "far"),
                new IconRecordModel(FontAwesomeIcon.DeleteTrashBold, "trash-alt"),
                new IconRecordModel(FontAwesomeIcon.DeleteTrashFull, "trash"),
                new IconRecordModel(FontAwesomeIcon.DeleteMinusCircleFull, "minus-circle"),
                new IconRecordModel(FontAwesomeIcon.DeleteMinus, "minus"),
                new IconRecordModel(FontAwesomeIcon.DeleteMinusSquare, "minus-square", "far"),
                new IconRecordModel(FontAwesomeIcon.DeleteMinusSquareFull, "minus-square"),
                new IconRecordModel(FontAwesomeIcon.DeleteUser, "user-times"),
                new IconRecordModel(FontAwesomeIcon.DeleteUserMinus, "user-minus"),
                new IconRecordModel(FontAwesomeIcon.Eye, "eye", "far"),
                new IconRecordModel(FontAwesomeIcon.EyeBold, "eye", "fas"),
                new IconRecordModel(FontAwesomeIcon.GoogleIcon, "google", "fab"),
                new IconRecordModel(FontAwesomeIcon.GooglePlay, "google-play", "fab"),
                new IconRecordModel(FontAwesomeIcon.GoogleDrive, "google-drive", "fab"),
                new IconRecordModel(FontAwesomeIcon.Database, "database"),
                new IconRecordModel(FontAwesomeIcon.Pager, "pager"),
                new IconRecordModel(FontAwesomeIcon.Tag, "tag"),
                new IconRecordModel(FontAwesomeIcon.Tags, "tags"),
                new IconRecordModel(FontAwesomeIcon.Teeth, "teeth"),
                new IconRecordModel(FontAwesomeIcon.InstagramIcon, "instagram", "fab"),
                new IconRecordModel(FontAwesomeIcon.InstagramSquare, "instagram-square", "fab"),
                new IconRecordModel(FontAwesomeIcon.Percentage, "percentage"),
                new IconRecordModel(FontAwesomeIcon.Hashtag, "hashtag"),
                new IconRecordModel(FontAwesomeIcon.Users, "users"),
                new IconRecordModel(FontAwesomeIcon.UserFriends, "user-friends"),
                new IconRecordModel(FontAwesomeIcon.Info, "info"),
                new IconRecordModel(FontAwesomeIcon.InfoCircle, "info-circle"),
                new IconRecordModel(FontAwesomeIcon.Image, "image", "far"),
                new IconRecordModel(FontAwesomeIcon.ImageFull, "image"),
                new IconRecordModel(FontAwesomeIcon.Images, "images", "far"),
                new IconRecordModel(FontAwesomeIcon.ImagesFull, "images"),
                new IconRecordModel(FontAwesomeIcon.Swatchbook, "swatchbook"),
                new IconRecordModel(FontAwesomeIcon.Key, "key"),
                new IconRecordModel(FontAwesomeIcon.Times, "times"),
                new IconRecordModel(FontAwesomeIcon.PhotoVideo, "photo-video"),
                new IconRecordModel(FontAwesomeIcon.PaintBrush, "paint-brush"),
                new IconRecordModel(FontAwesomeIcon.PaintBrushWide, "brush"),
                new IconRecordModel(FontAwesomeIcon.PaintRoller, "paint-roller"),
                new IconRecordModel(FontAwesomeIcon.Palette, "palette"),
                new IconRecordModel(FontAwesomeIcon.IdBadge, "id-badge", "far"),
                new IconRecordModel(FontAwesomeIcon.IdBadgeFull, "id-badge"),
                new IconRecordModel(FontAwesomeIcon.IdCard, "id-card", "far"),
                new IconRecordModel(FontAwesomeIcon.IdCardFull, "id-card"),
                new IconRecordModel(FontAwesomeIcon.Plus, "plus"),
                new IconRecordModel(FontAwesomeIcon.ArrowUpRightFromSquare, "arrow-up-right-from-square")
            });
            #endregion

            #region Font Awesome 6
            _iconArchive.AddRange(new IIconRecordModel[] {
                new IconRecordModel(FontAwesomeSixIcon.Recycle, "recycle"),
                new IconRecordModel(FontAwesomeSixIcon.Download, "download"),
                new IconRecordModel(FontAwesomeSixIcon.ArrowRight, "arrow-right"),
                new IconRecordModel(FontAwesomeSixIcon.ArrowLeft, "arrow-left"),
                new IconRecordModel(FontAwesomeSixIcon.ArrowUp, "arrow-up"),
                new IconRecordModel(FontAwesomeSixIcon.ArrowDown, "arrow-down"),
                new IconRecordModel(FontAwesomeSixIcon.RightToBracket, "right-to-bracket"),
                new IconRecordModel(FontAwesomeSixIcon.RightFromBraket, "right-from-bracket"),
                new IconRecordModel(FontAwesomeSixIcon.SignIn, "arrow-right-to-bracket"),
                new IconRecordModel(FontAwesomeSixIcon.SignOut, "arrow-right-from-bracket"),
                new IconRecordModel(FontAwesomeSixIcon.Building, "building", FontAwesomeSixPrefix.Regular),
                new IconRecordModel(FontAwesomeSixIcon.BuildingFull, "building"),
                new IconRecordModel(FontAwesomeSixIcon.Code, "code"),
                new IconRecordModel(FontAwesomeSixIcon.Bars, "bars"),
                new IconRecordModel(FontAwesomeSixIcon.File, "file"),
                new IconRecordModel(FontAwesomeSixIcon.Gear, "gear"),
                new IconRecordModel(FontAwesomeSixIcon.Gears, "gears"),
                new IconRecordModel(FontAwesomeSixIcon.Heart, "heart"),
                new IconRecordModel(FontAwesomeSixIcon.Barcode, "barcode"),
                new IconRecordModel(FontAwesomeSixIcon.Folder, "folder"),
                new IconRecordModel(FontAwesomeSixIcon.FolderOpen, "folder-open"),
                new IconRecordModel(FontAwesomeSixIcon.UserSecret, "user-secret"),
                new IconRecordModel(FontAwesomeSixIcon.NetowrkWired, "network-wired"),
                new IconRecordModel(FontAwesomeSixIcon.Sitemap, "sitemap"),
                new IconRecordModel(FontAwesomeSixIcon.Cube, "cube"),
                new IconRecordModel(FontAwesomeSixIcon.Cubes, "cubes"),
                new IconRecordModel(FontAwesomeSixIcon.Keyboard, "keyboard"),
                new IconRecordModel(FontAwesomeSixIcon.CodeBranch, "code-branch"),
                new IconRecordModel(FontAwesomeSixIcon.LaptopCode, "laptop-code"),
                new IconRecordModel(FontAwesomeSixIcon.FileLines, "file-lines"),
                new IconRecordModel(FontAwesomeSixIcon.FileCode, "file-code"),
                new IconRecordModel(FontAwesomeSixIcon.DiagromProject, "diagram-project"),
                new IconRecordModel(FontAwesomeSixIcon.BoxArchive, "box-archive"),
                new IconRecordModel(FontAwesomeSixIcon.YouTube, "youtube", FontAwesomeSixPrefix.Brands),
                new IconRecordModel(FontAwesomeSixIcon.YouTubeSquare, "square-youtube", FontAwesomeSixPrefix.Brands),
                new IconRecordModel(FontAwesomeSixIcon.Plus, "plus"),
                new IconRecordModel(FontAwesomeSixIcon.MoneyBill, "money-bill"),
                new IconRecordModel(FontAwesomeSixIcon.ArrowUpRightFromSquare, "arrow-up-right-from-square")
            });
            #endregion

            #region Ionicons
            _iconArchive.AddRange(new IIconRecordModel[] {
                new IconRecordModel(Ionicons.Accessibility, "accessibility"),
                new IconRecordModel(Ionicons.Add, "add"),
                new IconRecordModel(Ionicons.AddCircle, "add-circle"),
                new IconRecordModel(Ionicons.Airplane, "airplane"),
                new IconRecordModel(Ionicons.Alarm, "alarm"),
                new IconRecordModel(Ionicons.Albums, "albums"),
                new IconRecordModel(Ionicons.Alert, "alert"),
                new IconRecordModel(Ionicons.AlertCircle, "alert-circle"),
                new IconRecordModel(Ionicons.AlipayLogo, "logo-alipay"),
                new IconRecordModel(Ionicons.AmazonLogo, "logo-amazon"),
                new IconRecordModel(Ionicons.AmplifyLogo, "logo-amplify"),
                new IconRecordModel(Ionicons.AndroidLogo, "logo-android"),
                new IconRecordModel(Ionicons.AngularLogo, "logo-angular"),
                new IconRecordModel(Ionicons.AppleLogo, "logo-apple"),
                new IconRecordModel(Ionicons.AppleArLogo, "logo-apple-ar"),
                new IconRecordModel(Ionicons.AppstoreLogo, "logo-apple-appstore"),
                new IconRecordModel(Ionicons.BehanceLogo, "logo-behance"),
                new IconRecordModel(Ionicons.BitbucketLogo, "logo-bitbucket"),
                new IconRecordModel(Ionicons.BitcoinLogo, "logo-bitcoin"),
                new IconRecordModel(Ionicons.BufferLogo, "logo-buffer"),
                new IconRecordModel(Ionicons.CapacitorLogo, "logo-capacitor"),
                new IconRecordModel(Ionicons.ChromeLogo, "logo-chrome"),
                new IconRecordModel(Ionicons.CodepenLogo, "logo-codepen"),
                new IconRecordModel(Ionicons.CSS3Logo, "logo-css3"),
                new IconRecordModel(Ionicons.DesignerNewsLogo, "logo-designernews"),
                new IconRecordModel(Ionicons.DeviantArtLogo, "logo-deviantart"),
                new IconRecordModel(Ionicons.DiscordLogo, "logo-discord"),
                new IconRecordModel(Ionicons.DockerLogo, "logo-docker"),
                new IconRecordModel(Ionicons.DribbbleLogo, "logo-dribbble"),
                new IconRecordModel(Ionicons.DropboxLogo, "logo-dropbox"),
                new IconRecordModel(Ionicons.ElectronLogo, "logo-electron"),
                new IconRecordModel(Ionicons.EuroLogo, "logo-euro"),
                new IconRecordModel(Ionicons.FacebookLogo, "logo-facebook"),
                new IconRecordModel(Ionicons.FigmaLogo, "logo-figma"),
                new IconRecordModel(Ionicons.FirebaseLogo, "logo-firebase"),
                new IconRecordModel(Ionicons.FirefoxLogo, "logo-firefox"),
                new IconRecordModel(Ionicons.FlickrLogo, "logo-flickr"),
                new IconRecordModel(Ionicons.FoursquareLogo, "logo-foursquare"),
                new IconRecordModel(Ionicons.GithubLogo, "logo-github"),
                new IconRecordModel(Ionicons.GitlabLogo, "logo-gitlab"),
                new IconRecordModel(Ionicons.GoogleLogo, "logo-google"),
                new IconRecordModel(Ionicons.GooglePlaystoreLogo, "logo-google-playstore"),
                new IconRecordModel(Ionicons.HackerNewsLogo, "logo-hackernews"),
                new IconRecordModel(Ionicons.Html5Logo, "logo-html5"),
                new IconRecordModel(Ionicons.InstagramLogo, "logo-instagram"),
                new IconRecordModel(Ionicons.IonicLogo, "logo-ionic"),
                new IconRecordModel(Ionicons.IonitronLogo, "logo-ionitron"),
                new IconRecordModel(Ionicons.JavaScriptLogo, "logo-javascript"),
                new IconRecordModel(Ionicons.LaravelLogo, "logo-laravel"),
                new IconRecordModel(Ionicons.LinkedInLogo, "logo-linkedin"),
                new IconRecordModel(Ionicons.MarkdownLogo, "logo-markdown"),
                new IconRecordModel(Ionicons.MastodonLogo, "logo-mastodon"),
                new IconRecordModel(Ionicons.MediumLogo, "logo-medium"),
                new IconRecordModel(Ionicons.MicrosoftLogo, "logo-microsoft"),
                new IconRecordModel(Ionicons.NoSmokingLogo, "logo-no-smoking"),
                new IconRecordModel(Ionicons.NodeJsLogo, "logo-nodejs"),
                new IconRecordModel(Ionicons.NPMLogo, "logo-npm"),
                new IconRecordModel(Ionicons.OctocatLogo, "logo-octocat"),
                new IconRecordModel(Ionicons.PayPalLogo, "logo-paypal"),
                new IconRecordModel(Ionicons.PinterestLogo, "logo-pinterest"),
                new IconRecordModel(Ionicons.PlaystationLogo, "logo-playstation"),
                new IconRecordModel(Ionicons.PwaLogo, "logo-pwa"),
                new IconRecordModel(Ionicons.PythonLogo, "logo-python"),
                new IconRecordModel(Ionicons.ReactLogo, "logo-react"),
                new IconRecordModel(Ionicons.RedditLogo, "logo-reddit"),
                new IconRecordModel(Ionicons.RSSLogo, "logo-rss"),
                new IconRecordModel(Ionicons.SassLogo, "logo-sass"),
                new IconRecordModel(Ionicons.SkypeLogo, "logo-skype"),
                new IconRecordModel(Ionicons.SlackLogo, "logo-slack"),
                new IconRecordModel(Ionicons.SnapchatLogo, "logo-snapchat"),
                new IconRecordModel(Ionicons.SoundcloudLogo, "logo-soundcloud"),
                new IconRecordModel(Ionicons.StackoverflowLogo, "logo-stackoverflow"),
                new IconRecordModel(Ionicons.SteamLogo, "logo-steam"),
                new IconRecordModel(Ionicons.StencilLogo, "logo-stencil"),
                new IconRecordModel(Ionicons.TableauLogo, "logo-tableau"),
                new IconRecordModel(Ionicons.TikTokLogo, "logo-tiktok"),
                new IconRecordModel(Ionicons.TumblrLogo, "logo-tumblr"),
                new IconRecordModel(Ionicons.TuxLogo, "logo-tux"),
                new IconRecordModel(Ionicons.TwitchLogo, "logo-twitch"),
                new IconRecordModel(Ionicons.TwitterLogo, "logo-twitter"),
                new IconRecordModel(Ionicons.USDLogo, "logo-usd"),
                new IconRecordModel(Ionicons.VercelLogo, "logo-vercel"),
                new IconRecordModel(Ionicons.VenmoLogo, "logo-venmo"),
                new IconRecordModel(Ionicons.VimeoLogo, "logo-vimeo"),
                new IconRecordModel(Ionicons.VkLogo, "logo-vk"),
                new IconRecordModel(Ionicons.VueLogo, "logo-vue"),
                new IconRecordModel(Ionicons.WebComponentLogo, "logo-web-component"),
                new IconRecordModel(Ionicons.WechatLogo, "logo-wechat"),
                new IconRecordModel(Ionicons.WhatsAppLogo, "logo-whatsapp"),
                new IconRecordModel(Ionicons.WindowsLogo, "logo-windows"),
                new IconRecordModel(Ionicons.WordpressLogo, "logo-wordpress"),
                new IconRecordModel(Ionicons.XboxLogo, "logo-xbox"),
                new IconRecordModel(Ionicons.XingLogo, "logo-xing"),
                new IconRecordModel(Ionicons.YahooLogo, "logo-yahoo"),
                new IconRecordModel(Ionicons.YenLogo, "logo-yen"),
                new IconRecordModel(Ionicons.YoutubeLogo, "logo-youtube")
            });
            #endregion
            #endregion
        }

        #region Get Tags
        public ITagBuilderCustom GetFontAwesomeTag(FontAwesomeIcon icon)
        {
            ITagBuilderCustom result = new TagBuilderCustom("i");

            result.AddCssClassRange("creator-icon", "fa-icon", _iconArchive.Single(icn => icn.FontAwesomeIcon == icon).FontAwesomePrefix, $"fa-{_iconArchive.Single(icn => icn.FontAwesomeIcon == icon).Name}");

            return result;
        }

        public ITagBuilderCustom GetGoogleFontsIconsTag(GoogleFontsIcon icon)
        {
            ITagBuilderCustom result = new TagBuilderCustom("span");
            IIconRecordModel rec = _iconArchive.Single(icn => icn.GoogleFontsIcon == icon);

            result.AddCssClassRange("creator-icon", "material-symbols-outlined");
            result.ApplyContent(rec.Name);

            return result;
        }

        public ITagBuilderCustom GetCssGGIconTag(CssGGIcons icon)
        {
            ITagBuilderCustom result = new TagBuilderCustom("i");
            IIconRecordModel rec = _iconArchive.SingleOrDefault(icn => icn.CssGGIcon == icon);

            result.AddCssClassRange("creator-icon", rec.Name);

            return result;
        }

        public ITagBuilderCustom GetFontAwesomeSixTag(FontAwesomeSixIcon icon)
        {
            IIconRecordModel rec = _iconArchive.Single(icn => icn.FontAwesomeSixIcon == icon);
            ITagBuilderCustom result = new TagBuilderCustom("i");

            result.AddCssClassRange("creator-icon", rec.FontAwesomeSixPrefixAsString, $"{IconStatics.FontAwesomeSixIconPrefix}-{rec.Name}");

            return result;
        }

        public ITagBuilderCustom GetIoniconsTag(Ionicons icon, IoniconsStyle style)
        {
            IIconRecordModel rec = _iconArchive.Single(icn => icn.Ionicons == icon);
            ITagBuilderCustom result = new TagBuilderCustom("ion-icon");
            string name = rec.Name;

            if (style == IoniconsStyle.Outline)
            {
                name += "-outline";
            }
            else if (style == IoniconsStyle.Sharp)
            {
                name += "-sharp";
            }

            result.AddAttribute("name", name);
            result.AddCssClass("creator-icon");

            return result;
        }
        #endregion
    }

    #region Icon Enum's

    #region CssGGIcons

    /// <summary>
    /// List of all supported CSS GG icons
    /// </summary>
    public enum CssGGIcons
    {
        AddCircle,
        AddSquare,
        Adidas,
        Airplane,
        AlarmClock,
        Album,
        AlignBottom,
        AlignCenter,
        AlignLeft,
        AlignMiddle,
        AlignRight,
        AlignTop,
        Anchor,
        AppleWatch,
        ArrowBottomLeft,
        ArrowBottomLeftCircle,
        ArrowBottomLeftSquare,
        ArrowBottomRight,
        ArrowBottomRightCircle,
        ArrowBottomRightSquare,
        ArrowDown,
        ArrowDownCircle,
        ArrowDownSquare,
        ArrowLeft,
        ArrowLeftCircle,
        ArrowLeftSquare,
        ArrowRight,
        ArrowRightCircle,
        ArrowRightSquare,
        ArrowTopLeft,
        ArrowTopLeftCircle,
        ArrowTopLeftSquare,
        ArrowUp,
        ArrowUpCircle,
        ArrowUpSquare,
        Attachment,
        Backspace,
        BarsMenu,
        BarsMenuBoxed,
        BarsMenuRound,
        Battery,
        BatteryEmpty,
        BatteryFull,
        Bell,
        Bitbucket,
        Block,
        BMW,
        Board,
        Bolt,
        Bot,
        Bowl,
        Box,
        Brackets,
        Briefcase,
        Browse,
        Browser,
        Brush,
        Bulb,
        Calculator,
        Calendar,
        Camera,
        Cap,
        Chanel,
        Chart,
        Check,
        CheckCircle,
        CheckSquare,
        ChevronDoubleDown,
        ChevronDoubleDownCircle,
        ChevronDoubleDownSquare,
        ChevronDoubleLeft,
        ChevronDoubleLeftCircle,
        ChevronDoubleLeftSquare,
        ChevronDoubleRight,
        ChevronDoubleRightCircle,
        ChevronDoubleRightSquare,
        ChevronDoubleUp,
        ChevronDoubleUpCircle,
        ChevronDoubleUpSquare,
        ChevronDown,
        ChevronDownCircle,
        ChevronDownSquare,
        ChevronLeft,
        ChevronLeftCircle,
        ChevronLeftSquare,
        ChevronRight,
        ChevronRightCircle,
        ChevronRightSquare,
        ChevronUp,
        ChevronUpCircle,
        ChevronUpSquare,
        Circleci,
        Clipboard,
        Close,
        CloseCircle,
        CloseSquare,
        Cloud,
        Code,
        Coffee,
        ComedyCentral,
        Comment,
        Copy,
        Copyright,
        Cplusplus,
        CreditCard,
        Crowdfire,
        Danger,
        DarkMode,
        Database,
        Debug,
        Designmodo,
        Desktop,
        Dialpad,
        DiceFive,
        DiceFour,
        DiceOne,
        DiceSix,
        DiceThree,
        DiceTwo,
        Digitalocean,
        DisplayGrid,
        Document,
        DocumentAdd,
        DocumentAlt,
        DocumentRemove,
        Dolby,
        Dollar,
        Download,
        Drive,
        Duplicate,
        Envelope,
        EnvelopeOpen,
        Erase,
        Ereader,
        Ericsson,
        Ethernet,
        Euro,
        Eventbrite,
        Export,
        Eye,
        EyeAlt,
        Facebook,
        Feed,
        Figma,
        Games,
        GenderFemale,
        GenderMale,
        Ghost,
        Gift,
        Globe,
        GlobeAlt,
        Google,
        Hashtag,
        Heart,
        Home,
        HomeAlt,
        Image,
        Import,
        Inbox,
        Infinity,
        Info,
        Insights,
        Instagram,
        Key,
        Laptop,
        Link,
        List,
        ListSquare,
        ListTree,
        Loadbar,
        LoadbarDoc,
        LoadbarSound,
        LockLocked,
        LockUnlocked,
        LogOff,
        Magnet,
        Mic,
        Microbit,
        Microsoft,
        Modem,
        Moon,
        More,
        MoreCircle,
        MoreSquare,
        MoveDown,
        MoveLeft,
        MoveRight,
        MoveUp,
        None,
        Note,
        NoteDouble,
        Notes,
        Notification,
        Npm,
        Oculus,
        Organisation,
        Password,
        Patreon,
        Pause,
        PauseCircle,
        PauseSquare,
        PayPal,
        Pen,
        Pexels,
        Phone,
        Play,
        PlayCircle,
        PlaySquare,
        Pokemon,
        Polaroid,
        Poll,
        Printer,
        Profile,
        QrCode,
        Radio,
        RadioChecked,
        Ratio,
        Readme,
        Redo,
        RemoveCircle,
        RemoveSquare,
        Rename,
        Repeat,
        Screen,
        ScreenWide,
        Search,
        Server,
        Settings,
        SignIn,
        SignOut,
        Smartphone,
        Smile,
        SmileNeutral,
        SmileNoMouth,
        SmileNone,
        SmileOpen,
        SmileSad,
        SmileUpside,
        Speaker,
        Stop,
        StopCircle,
        StopSquare,
        Support,
        ToggleOff,
        ToggleOn,
        Trash,
        TrashEmpty,
        Trello,
        TrendingDown,
        TrendingUp,
        TV,
        Twilio,
        Twitter,
        UiKit,
        Undo,
        Upload,
        User,
        UserAdd,
        UserList,
        UserRemove,
        ViewCols,
        ViewComfortable,
        ViewDay,
        ViewGrid,
        ViewList,
        ViewMonth,
        ViewSplit,
        Website,
        Windows,
        Work,
        YinYang,
        YouTube,
        Zoom,
        ZoomOut
    }

    #endregion

    #region GoogleFontsIcon

    /// <summary>
    /// List of all supported Google Material symbols
    /// </summary>
    public enum GoogleFontsIcon
    {
        ABC,
        AccountTree,
        Airplane,
        AngleDown,
        AngleLeft,
        AngleRight,
        AngleUp,
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        Article,
        AttachFile,
        AttachFileAdd,
        BarChart,
        Bars,
        Basketball,
        Calendar,
        Cellphone,
        CellphoneAndroid,
        Chat,
        Check,
        CheckBox,
        CheckSmall,
        Close,
        Code,
        Comment,
        Computer,
        Contacts,
        Copy,
        Copyright,
        CreditCard,
        CSS,
        Database,
        Dataset,
        DatasetLinked,
        Document,
        ErrorCircle,
        EventList,
        Family,
        FileOpen,
        Football,
        Grid,
        GridSmall,
        HeartCheck,
        HelpCircle,
        Home,
        Hub,
        Image,
        ImagePanorama,
        Images,
        InfoCircle,
        Javascript,
        Language,
        Laptop,
        Lightbulb,
        Link,
        List,
        ListFormatted,
        ListFormattedNumbered,
        Login,
        Logout,
        Mail,
        MailUnsubscribe,
        Man,
        Monitor,
        None,
        Payments,
        Phone,
        Preview,
        Psychology,
        Refresh,
        Save,
        Search,
        Security,
        Settings,
        Shield,
        ShoppingBag,
        ShoppingCart,
        ShoppingCartAdd,
        ShoppingCartCheckout,
        Tag,
        TuneSettings,
        Upload,
        User,
        UserAdd,
        UserBox,
        UserCheck,
        UserCircle,
        UserGroup,
        UserGroups,
        UserMail,
        UserRemove,
        UserSearch,
        UserSettings,
        Verified,
        Warning,
        Woman,
    }

    #endregion

    #region FontAwesome

    /// <summary>
    /// Supported FontAwesome icons
    /// </summary>
    public enum FontAwesomeIcon
    {
        Add,
        AddCircle,
        AddCircleFull,
        AddFull,
        AddressBook,
        AddressBookFull,
        AddressCard,
        AddressCardFull,
        AmazonPay,
        AmazonPayIcon,
        AmericanExpress,
        AngleDown,
        AngleLeft,
        AngleRight,
        AngleUp,
        ApplePay,
        ApplePayIcon,
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        ArrowUpRightFromSquare,
        Bars,
        BorderAll,
        Box,
        Boxes,
        BoxOpen,
        Building,
        BuildingFull,
        Bullhorn,
        Calendar,
        CalendarFull,
        Camera,
        Check,
        CheckCircle,
        CheckCircleFull,
        CheckSquare,
        CheckSquareFull,
        Close,
        CloseCircle,
        CloseCircleFull,
        CloseFull,
        Code,
        Cogs,
        Comment,
        CommentFull,
        Comments,
        CommentsFull,
        Copy,
        CopyFull,
        CreditCard,
        Database,
        DeleteMinus,
        DeleteMinusCircleFull,
        DeleteMinusSquare,
        DeleteMinusSquareFull,
        DeleteTrash,
        DeleteTrashBold,
        DeleteTrashFull,
        DeleteUser,
        DeleteUserMinus,
        Diagram,
        Doc,
        DocCode,
        DocImage,
        DocPDF,
        Download,
        DownloadCloud,
        Edit,
        EditFull,
        Envelope,
        EnvelopeFull,
        EnvelopeOpen,
        EnvelopeOpenFull,
        Eye,
        EyeBold,
        FacebookLogo,
        FacebookLogoCircle,
        FacebookLogoSquare,
        FileAlt,
        FileDownload,
        FileExport,
        FileImage,
        FileImageFull,
        FileUpload,
        Folder,
        FolderFull,
        FolderMinusFull,
        FolderOpen,
        FolderOpenFull,
        FolderPlusFull,
        Gear,
        Ghost,
        GitHub,
        Globe,
        GlobeEurope,
        GoogleDrive,
        GoogleIcon,
        GooglePlay,
        GoogleWallet,
        Handshake,
        HandshakeFull,
        Hashtag,
        Home,
        HomeDamage,
        IdBadge,
        IdBadgeFull,
        IdCard,
        IdCardFull,
        Image,
        ImageFull,
        Images,
        ImagesFull,
        Info,
        InfoCircle,
        InstagramIcon,
        InstagramSquare,
        Key,
        LaptopCode,
        Like,
        LikeFull,
        LinkedInLogo,
        LinkedInLogoSquare,
        List,
        ListAlt,
        ListAltFull,
        Lock,
        LockOpen,
        Mastercard,
        Messenger,
        Mobile,
        MobileFull,
        MoneyBill,
        None,
        Pager,
        PaintBrush,
        PaintBrushWide,
        PaintRoller,
        Palette,
        PayPal,
        PayPalIcon,
        Percentage,
        Phone,
        PhoneFull,
        PhotoVideo,
        Plus,
        Save,
        SaveFull,
        Search,
        SearchDollar,
        SearchLocation,
        SearchMinus,
        SearchPlus,
        ShieldAlt,
        ShieldVirus,
        ShoppingBag,
        ShoppingBasket,
        ShoppingCart,
        ShoppingCartPlus,
        SignIn,
        SignOut,
        Smile,
        SmileFull,
        SmileLaugh,
        SmileLaughFull,
        SmileWink,
        SmileWinkFull,
        Stripe,
        Swatchbook,
        Tag,
        Tags,
        Tasks,
        Teeth,
        ThumbsDown,
        ThumbsDownFull,
        Thumbstick,
        ThumbsUp,
        ThumbsUpFull,
        Times,
        Tools,
        Truck,
        Upload,
        UploadCloud,
        User,
        UserCircle,
        UserCircleFull,
        UserFriends,
        UserFull,
        UserLock,
        UserNinja,
        UserPlusFull,
        Users,
        UserShield,
        UserSpy,
        UserTie,
        Visa,
        X,
    }

    #endregion

    #region FontAwesomeSix

    /// <summary>
    /// List of the new style Font Awesome icons
    /// </summary>
    public enum FontAwesomeSixIcon
    {
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        ArrowUpRightFromSquare,
        Barcode,
        Bars,
        BoxArchive,
        Building,
        BuildingFull,
        Code,
        CodeBranch,
        Cube,
        Cubes,
        DiagromProject,
        Download,
        File,
        FileCode,
        FileLines,
        Folder,
        FolderOpen,
        Gear,
        Gears,
        Heart,
        Keyboard,
        LaptopCode,
        MoneyBill,
        NetowrkWired,
        None,
        Plus,
        Recycle,
        RightFromBraket,
        RightToBracket,
        SignIn,
        SignOut,
        Sitemap,
        UserSecret,
        YouTube,
        YouTubeSquare,
    }

    #endregion

    #region Ionicons

    /// <summary>
    /// List of all suported Ionicons
    /// </summary>
    public enum Ionicons
    {
        Accessibility,
        Add,
        AddCircle,
        Airplane,
        Alarm,
        Albums,
        Alert,
        AlertCircle,
        AlipayLogo,
        AmazonLogo,
        AmplifyLogo,
        AndroidLogo,
        AngularLogo,
        AppleArLogo,
        AppleLogo,
        AppstoreLogo,
        BehanceLogo,
        BitbucketLogo,
        BitcoinLogo,
        BufferLogo,
        CapacitorLogo,
        ChromeLogo,
        CodepenLogo,
        CSS3Logo,
        DesignerNewsLogo,
        DeviantArtLogo,
        DiscordLogo,
        DockerLogo,
        DribbbleLogo,
        DropboxLogo,
        ElectronLogo,
        EuroLogo,
        FacebookLogo,
        FigmaLogo,
        FirebaseLogo,
        FirefoxLogo,
        FlickrLogo,
        FoursquareLogo,
        GithubLogo,
        GitlabLogo,
        GoogleLogo,
        GooglePlaystoreLogo,
        HackerNewsLogo,
        Html5Logo,
        InstagramLogo,
        IonicLogo,
        IonitronLogo,
        JavaScriptLogo,
        LaravelLogo,
        LinkedInLogo,
        MarkdownLogo,
        MastodonLogo,
        MediumLogo,
        MicrosoftLogo,
        NodeJsLogo,
        None,
        NoSmokingLogo,
        NPMLogo,
        OctocatLogo,
        PayPalLogo,
        PinterestLogo,
        PlaystationLogo,
        PwaLogo,
        PythonLogo,
        ReactLogo,
        RedditLogo,
        RSSLogo,
        SassLogo,
        SkypeLogo,
        SlackLogo,
        SnapchatLogo,
        SoundcloudLogo,
        StackoverflowLogo,
        SteamLogo,
        StencilLogo,
        TableauLogo,
        TikTokLogo,
        TumblrLogo,
        TuxLogo,
        TwitchLogo,
        TwitterLogo,
        USDLogo,
        VenmoLogo,
        VercelLogo,
        VimeoLogo,
        VkLogo,
        VueLogo,
        WebComponentLogo,
        WechatLogo,
        WhatsAppLogo,
        WindowsLogo,
        WordpressLogo,
        XboxLogo,
        XingLogo,
        YahooLogo,
        YenLogo,
        YoutubeLogo
    }

    #endregion

    #endregion

    #region Enums

    /// <summary>
    /// Types of unique Ionicon styles
    /// </summary>
    public enum IoniconsStyle
    {
        Outline,
        Filled,
        Sharp
    }

    /// <summary>
    /// Font Awesome Six prefixes
    /// </summary>
    public enum FontAwesomeSixPrefix
    {
        Solid,
        Regular,
        Brands
    }

    #endregion
}
